- name: Scan
  uses: ShiftLeftSecurity/scan-action@master
  env:
    WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SCAN_AUTO_BUILD: true
  with:
    output: reports

- name: Update scan baseline on main branch
  if: {{ github.ref == 'refs/heads/main' }}
  run: |
    cp reports/.sastscan.baseline .

    git config --global user.name "scan+github-actions[bot]"
    git config --global user.email "scan+github-actions[bot]@users.noreply.github.com"

    git add .sastscan.baseline
    git commit -m "Update scan baseline"
    git push
